apiVersion: v1
kind: Service
metadata:
  name: pathfinder-service
spec:
  type: NodePort
  selector:
    app: pathfinder
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
    nodePort: 30080